# Generated by Django 6.0.8 on 2026-09-28 17:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('equipment.manage', 'Manage equipment'), ('users.manage', 'Manage users'), ('inquiries.manage', 'Manage inquiries'), ('deals.manage', 'Manage deals')], max_length=32), blank=True, default=list, help_text="Permission codes granted inside the user's own organization. Ignored for the owner, who implicitly holds all of them."),
        ),
    ]
