# Generated by Django 6.0.5 on 2026-07-20 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed')], db_index=True, max_length=20)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='str() of the target when the action happened', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Field-level diff: {"field": {"from": ..., "to": ...}}')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Request metadata (ip, user agent, endpoint, …)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action; null once the account is deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users.organization')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='core_activi_organiz_159c1c_idx'), models.Index(fields=['content_type', 'object_id'], name='core_activi_content_1a7154_idx')],
            },
        ),
    ]
