# Generated by Django 6.0.8 on 2026-09-28 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0003_backfill_opening_messages'),
        ('listings', '0005_alter_listing_status'),
        ('users', '0010_alter_user_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('deal_type', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=10)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending confirmation'), ('completed', 'Completed'), ('declined', 'Declined')], db_index=True, default='pending_confirmation', max_length=24)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The provider-side member who turned the inquiry into a deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL)),
                ('customer_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals_as_customer', to='users.organization')),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='inquiries.inquiry')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='listings.listing')),
                ('provider_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals_as_provider', to='users.organization')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_written', to='users.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_created', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='deals.deal')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['provider_organization', '-completed_at'], name='deal_provider_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['customer_organization', 'status'], name='deal_customer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('customer_organization', models.F('provider_organization')), _negated=True), name='deal_not_own_org'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.UniqueConstraint(condition=models.Q(('inquiry__isnull', False)), fields=('inquiry',), name='deal_one_per_inquiry'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range'),
        ),
    ]
