# Generated by Django 6.0.5 on 2026-07-11 11:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_organization_name_alter_organization_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_unit', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('hectare', 'Per Hectare'), ('shift', 'Per Shift'), ('operation', 'Per Operation'), ('km', 'Per Kilometre')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meter_start', models.DecimalField(blank=True, decimal_places=1, help_text='Meter hours at rental start', max_digits=9, null=True)),
                ('meter_end', models.DecimalField(blank=True, decimal_places=1, help_text='Meter hours at rental end', max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DepositRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('is_refundable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('rental_contract', 'Rental Contract'), ('equipment_registration', 'Equipment Registration'), ('insurance', 'Insurance'), ('inspection_photo', 'Inspection Photo'), ('maintenance_doc', 'Maintenance Document'), ('operator_license', 'Operator License'), ('other', 'Other')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_self_propelled', models.BooleanField(default=False, help_text='True for tractors, combines, sprayers; False for towed/mounted implements.')),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Model name, e.g. '8R 410'", max_length=120)),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, help_text='Null = still in production', null=True)),
                ('engine_power_kw', models.DecimalField(blank=True, decimal_places=1, help_text='Engine power in kilowatts', max_digits=7, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('working_width_mm', models.PositiveIntegerField(blank=True, help_text='Working width for seeders, sprayers, cultivators, etc.', null=True)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('na', 'N/A (implement)')], default='diesel', max_length=10)),
                ('is_self_propelled', models.BooleanField(default=False)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text="Category-specific attributes. E.g. {'furrows': 5} for a plough, {'rows': 12, 'row_spacing_cm': 70} for a seeder.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModelCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_type', models.CharField(choices=[('tractor_implement', 'Tractor → Implement'), ('combine_header', 'Combine → Header'), ('other', 'Other')], max_length=30)),
                ('min_power_kw', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('max_power_kw', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('hitch_category', models.CharField(blank=True, choices=[('cat1', 'Category 1'), ('cat2', 'Category 2'), ('cat3', 'Category 3'), ('cat4', 'Category 4'), ('drawbar', 'Drawbar')], max_length=10)),
                ('pto_speed_rpm', models.PositiveSmallIntegerField(blank=True, help_text='Required PTO speed: 540 or 1000', null=True)),
                ('hydraulic_flow_l_min', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('isobus_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Equipment Model Compatibility',
                'verbose_name_plural': 'Equipment Model Compatibilities',
            },
        ),
        migrations.CreateModel(
            name='ExternalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('external_system', models.CharField(choices=[('john_deere', 'John Deere Operations Center'), ('claas', 'CLAAS'), ('cnh', 'CNH / Case IH / New Holland'), ('adapt', 'ADAPT'), ('isobus', 'ISOBUS / ISOXML'), ('gps_tracker', 'GPS Tracker'), ('other', 'Other')], max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('external_version', models.CharField(blank=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Last raw payload received from the external system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('pre_rental', 'Pre-Rental'), ('post_rental', 'Post-Rental'), ('routine', 'Routine')], max_length=20)),
                ('inspected_at', models.DateTimeField()),
                ('condition_status', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20)),
                ('checklist', models.JSONField(blank=True, default=dict, help_text="Structured checklist, e.g. {'tyres': 'ok', 'lights': 'damaged', 'hydraulics': 'ok'}")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('scheduled', 'Scheduled Service'), ('repair', 'Repair'), ('emergency', 'Emergency Repair'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('meter_hours_at_service', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('performed_by', models.CharField(blank=True, help_text='Technician name or service centre', max_length=255)),
                ('next_service_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Schedule next service at this meter reading', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_unit', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('hectare', 'Per Hectare'), ('shift', 'Per Shift'), ('operation', 'Per Operation'), ('km', 'Per Kilometre')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('includes_operator', models.BooleanField(default=False)),
                ('includes_fuel', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['organization', 'pricing_unit'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('ploughing', 'Ploughing'), ('seeding', 'Seeding'), ('spraying', 'Spraying'), ('harvesting', 'Harvesting'), ('cultivating', 'Cultivating'), ('baling', 'Baling'), ('transport', 'Transport'), ('fertilizing', 'Fertilizing'), ('other', 'Other')], max_length=30)),
                ('planned_start_at', models.DateTimeField()),
                ('planned_end_at', models.DateTimeField()),
                ('planned_area_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Planned area in hectares', max_digits=10, null=True)),
                ('required_depth_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Required working depth in cm (ploughing, cultivating)', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['planned_start_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_meter_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('end_meter_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('area_completed_ha', models.DecimalField(blank=True, decimal_places=4, help_text='Hectares completed in this session', max_digits=10, null=True)),
                ('fuel_used_l', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel consumed in litres', max_digits=8, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance travelled in kilometres', max_digits=8, null=True)),
                ('track_geometry', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, help_text='GPS track recorded during this session (WGS84)', null=True, srid=4326)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('mobile_app', 'Mobile App'), ('gps_tracker', 'GPS Tracker'), ('isobus', 'ISOBUS'), ('manufacturer_api', 'Manufacturer API')], default='manual', max_length=20)),
                ('external_reference', models.CharField(blank=True, help_text='ID in the source system (e.g. ISOBUS task file ID)', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('vin_or_pin', models.CharField(blank=True, db_index=True, help_text='VIN (vehicles) or PIN (Product Identification Number)', max_length=64)),
                ('internal_inventory_number', models.CharField(blank=True, max_length=64)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('manufacture_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ownership_status', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('financed', 'Financed')], default='owned', max_length=20)),
                ('operational_status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('rented', 'Rented'), ('in_transit', 'In Transit'), ('under_maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service'), ('retired', 'Retired')], db_index=True, default='available', max_length=20)),
                ('current_meter_hours', models.DecimalField(decimal_places=1, default=0, help_text='Engine / meter hours at last update', max_digits=9)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Last known location (WGS84). Updated on lifecycle events, not live.', null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='users.organization')),
            ],
            options={
                'ordering': ['organization', 'equipment_model__name'],
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('checked_out', 'Checked Out'), ('delivered', 'Delivered'), ('work_started', 'Work Started'), ('work_completed', 'Work Completed'), ('fuel_added', 'Fuel Added'), ('fault_detected', 'Fault Detected'), ('maintenance_started', 'Maintenance Started'), ('maintenance_completed', 'Maintenance Completed'), ('returned', 'Returned')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Event-specific data (meter hours, fuel quantity, etc.)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='equipment.asset')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked (manual)'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_periods', to='equipment.asset')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disputed', 'Disputed')], db_index=True, default='draft', max_length=20)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('operator_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('customer_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_customer', to='users.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
