# Generated by Django 6.0.5 on 2026-07-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('equipment', '0001_initial'),
        ('farms', '0001_initial'),
        ('users', '0003_alter_organization_name_alter_organization_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_provider', to='users.organization'),
        ),
        migrations.AddField(
            model_name='assetevent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='equipment.booking'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='equipment.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositrule',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposit_rules', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='depositrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_rules', to='users.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='equipment.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='equipment.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='equipmentmodelcompatibility',
            name='compatible_with',
            field=models.ForeignKey(blank=True, help_text='Specific tractor model; null = requirements apply to any tractor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_tractor', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='equipmentmodelcompatibility',
            name='primary_model',
            field=models.ForeignKey(help_text='The implement / attachment that has requirements', on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_implement', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='externalreference',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='faultreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fault_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='equipment.booking'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='equipment.manufacturer'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='equipment_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='equipment.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='users.organization'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='equipment.booking'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='farms.field'),
        ),
        migrations.AddField(
            model_name='assetevent',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='equipment.workorder'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worksession',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='equipment.workorder'),
        ),
        migrations.AddIndex(
            model_name='availabilityperiod',
            index=models.Index(fields=['asset', 'starts_at', 'ends_at'], name='equipment_a_asset_i_1f747f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_at'], name='equipment_b_status_f12cad_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_organization', 'status'], name='equipment_b_custome_13c687_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['provider_organization', 'status'], name='equipment_b_provide_8d018c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='equipment_d_content_573830_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['operational_status'], name='equipment_a_operati_f6fd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'operational_status'], name='equipment_a_organiz_dc4765_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['external_system', 'external_id'], name='equipment_e_externa_a5a3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreference',
            index=models.Index(fields=['content_type', 'object_id'], name='equipment_e_content_3e9f6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalreference',
            unique_together={('content_type', 'object_id', 'external_system', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['category', 'is_self_propelled'], name='equipment_e_categor_158a98_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['engine_power_kw'], name='equipment_e_engine__cc9684_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentmodel',
            unique_together={('manufacturer', 'name')},
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['asset', 'pricing_unit'], name='equipment_p_asset_i_13de2b_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['equipment_model', 'pricing_unit'], name='equipment_p_equipme_569420_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['booking', 'status'], name='equipment_w_booking_8bc186_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['farm', 'planned_start_at'], name='equipment_w_farm_id_e352d0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetevent',
            index=models.Index(fields=['asset', 'occurred_at'], name='equipment_a_asset_i_927258_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['work_order', 'started_at'], name='equipment_w_work_or_f4a515_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['asset', 'started_at'], name='equipment_w_asset_i_d02427_idx'),
        ),
    ]
