# Generated by Django 6.0.5 on 2026-07-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='hitch_category',
            field=models.CharField(blank=True, choices=[('cat1', 'Category 1'), ('cat2', 'Category 2'), ('cat3', 'Category 3'), ('cat4', 'Category 4'), ('drawbar', 'Drawbar')], help_text='Hitch this machine PROVIDES (tractors). Blank for implements — what an implement REQUIRES lives in EquipmentModelCompatibility.', max_length=10),
        ),
    ]
