# Generated by Django 6.0.5 on 2026-08-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentmodel_hitch_category'),
        ('users', '0004_public_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('asset__isnull', False), ('equipment_model__isnull', False), _connector='OR'), name='pricingrule_has_target', violation_error_message='A pricing rule must target either an asset or an equipment model.'),
        ),
    ]
