# Generated by Django 6.0.5 on 2026-08-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_pricingrule_pricingrule_has_target'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['operational_status', '-created_at'], name='asset_status_created_idx'),
        ),
    ]
