# Generated by Django 6.0.8 on 2026-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_document_organization_required'),
        ('users', '0008_region_slug_soato'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('id', 'organization'), name='asset_id_org_unique'),
        ),
    ]
