"""
Django settings for agro project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ["*"]
ENVIRONMENT = os.environ.get('ENVIRONMENT', default='development')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'django.contrib.gis',
    # Registers the ArrayField lookups used by users.User.permissions.
    'django.contrib.postgres',

    'corsheaders',

    # Local
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',
    'api.apps.ApiConfig',
    'farms.apps.FarmsConfig',
    'equipment.apps.EquipmentConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Only the public marketing site needs cross-origin access — everything else
# (the app frontend, mobile clients) talks to the API same-origin or via a
# bearer token, which CORS doesn't gate anyway.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    "https://api.agronome.uz",
    "https://agronome.uz",
    "http://framework:8081",
    "http://localhost:8081",
]

ROOT_URLCONF = 'agro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
        "CONN_MAX_AGE": int(os.environ.get("CONN_MAX_AGE") or 0),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

# STORAGES = {
#     "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
#     "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
# }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# One-time passcodes — phone + OTP is the default login (api/otp.py).
# The limits below are enforced by counting `api.PhoneOtp` rows, not from the
# cache: OTP volume is low, the counts are indexed, and a database-backed
# limit holds across processes and restarts without extra infrastructure.
OTP_CODE_LENGTH = 6
OTP_TTL_SECONDS = 5 * 60
# How long a client must wait before asking for another code for the same
# number. Returned as `retry_after` so the UI can show a countdown.
OTP_RESEND_COOLDOWN_SECONDS = 60
# Wrong guesses allowed against a single code before it is burnt.
OTP_MAX_ATTEMPTS = 5
OTP_MAX_REQUESTS_PER_PHONE_PER_HOUR = 5
OTP_MAX_REQUESTS_PER_IP_PER_HOUR = 30
# Proof-of-phone-ownership handed to /auth/org/signup. Short, single-use.
SIGNUP_TOKEN_TTL_SECONDS = 15 * 60

# Escape hatches for developing without an SMS gateway. Both are refused
# when ENVIRONMENT is 'production' — here *and* again at the point of use in
# api/sms.py, because a leaked passcode is a live credential: whoever reads
# it can post it to the public /auth/otp/verify and hold that person's
# tokens. Neither is tied to DEBUG; DEBUG is about error pages.
#
# Numbers listed here receive the fixed `OTP_DEV_CODE` instead of a random
# one. The list is empty by default, so the predictable code can only reach
# a number someone named on purpose — and since the API returns the code for
# exactly these numbers, keep real users off the list.
OTP_DEV_CODE = os.environ.get('OTP_DEV_CODE', '000000')
OTP_TEST_PHONES = [
    phone.strip()
    for phone in os.environ.get('OTP_TEST_PHONES', '').split(',')
    if phone.strip()
]

# Writes real passcodes for *any* number to the log. The only way to sign in
# as a number that isn't whitelisted while the gateway is mocked, and the
# most dangerous setting in this file — anyone who can read the logs can take
# over any account. Off unless explicitly asked for, and never in production.
OTP_ECHO_CODES = (
    os.environ.get('OTP_ECHO_CODES', 'False').lower() in ('true', '1', 'yes')
    and ENVIRONMENT != 'production'
)

# The mocked gateway reports undelivered messages at WARNING, which Django's
# defaults would route to the console anyway; this pins the level so the
# reports can't be lost, and keeps the logger addressable by name for
# anything that wants to route it elsewhere. It carries no message bodies —
# see api/sms.py.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'api.sms': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}

if ENVIRONMENT == 'production':
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
